name: Deploy Nooble_ui App

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    name: Build Vue.js Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found, running npm install..."
            npm install
          else
            npm ci
          fi

      - name: Build Vue.js app
        run: npm run build

      # On enregistre le dossier dist tel quel
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist_folder
          path: dist/

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # On télécharge l'artefact du build (le dossier dist)
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist_folder

      # (Optionnel) Vérification du contenu
      - name: List files
        run: ls -R

      - name: Install lftp
        run: sudo apt-get install -y lftp

      # Déploiement
      # On met le contenu de dist dans le dossier nooble-ui sur le serveur
      # sans créer de sous-dossier dist supplémentaire.
      - name: Deploy via SFTP to nooble-ui folder
        env:
          IUT_USER: ${{ secrets.IUT_USER }}
          IUT_PASSW: ${{ secrets.IUT_PASSW }}
        run: |
          echo "Starting deployment..."
          lftp -u $IUT_USER,$IUT_PASSW sftp://ftpinfo.iutmontp.univ-montp2.fr -e "
            set ftp:ssl-allow 0;
            set sftp:auto-confirm yes;
            cd public_html;
            mkdir -p nooble-ui;
            mirror --reverse --verbose dist nooble-ui
            bye
          "
