name: Deploy Nooble_ui App

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    name: Build Vue.js Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found, running npm install..."
            npm install
          else
            npm ci
          fi

      - name: Build Vue.js app
        run: npm run build

      - name: Archive build
        run: zip -r nooble_ui.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nooble_ui
          path: nooble_ui.zip

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nooble_ui

      - name: Unzip artifact
        run: unzip nooble_ui.zip

      - name: Create index.html
        run: echo "<a href=\"nooble_ui.zip\">Last version -> nooble_ui.zip </a>" > index.html

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy via SFTP
        env:
          IUT_USER: ${{ secrets.IUT_USER }}
          IUT_PASSW: ${{ secrets.IUT_PASSW }}
        run: |
          echo "Starting deployment..."
          lftp -u $IUT_USER,$IUT_PASSW sftp://ftpinfo.iutmontp.univ-montp2.fr -e "
            set ftp:ssl-allow 0;
            set sftp:auto-confirm yes;
            cd public_html;
            put nooble_ui.zip;
            put index.html;
            bye
          "
