name: Deploy Nooble_ui App

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    name: Build Vue.js Application
    runs-on: ubuntu-latest

    steps:
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Vue.js app
        run: npm run build

      - name: Archive build
        run: zip -r nooble_ui.zip dist


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nooble_ui
          path: nooble_ui.zip

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Install lftp
        run: sudo apt-get install -y lftp


      - name: Deploy via SFTP
        env:
          IUT_USER: ${{ secrets.IUT_USER }}
          IUT_PASSW: ${{ secrets.IUT_PASSW }}
        run: |
          echo "Starting deployment..."

          lftp -u $IUT_USER,$IUT_PASSW -e "
            set ftp:ssl-allow no;


            cd public_html || mkdir public_html;
            cd public_html;
            if [ -e nooble_ui ]; then
              rm -r nooble_ui;
            fi


            mkdir -p nooble_ui;
            cd nooble_ui;
            mirror --reverse --delete --verbose dist .;

            bye;
          " sftp://ftpinfo.iutmontp.univ-montp2.fr
